// Code generated by envgen. DO NOT EDIT.

package tel

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := ReloadConfig(&cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	return loadConfig(cfg, env.Snapshot())
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "MONITOR_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.MonitorConfig.MonitorAddr = "127.0.0.1:8011"
		} else {
			cfg.MonitorConfig.MonitorAddr = raw
		}
	}
	{
		key := "MONITOR_ENABLE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "MonitorConfig.Enable", key, "true", err)
			} else {
				cfg.MonitorConfig.Enable = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MonitorConfig.Enable", key, raw, err)
			} else {
				cfg.MonitorConfig.Enable = v
			}
		}
	}
	{
		key := "TEL_COLLECTOR_GRPC_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.TelConfig.Address = "127.0.0.1:4317"
		} else {
			cfg.TelConfig.Address = raw
		}
	}
	{
		key := "TEL_COLLECTOR_TLS_SERVER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.TelConfig.ServerName = raw
		}
	}
	{
		key := "TEL_METRIC_PERIODIC_INTERVAL_SEC"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("15")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.MetricsPeriodicIntervalSec", key, "15", err)
			} else {
				cfg.TelConfig.MetricsPeriodicIntervalSec = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.MetricsPeriodicIntervalSec", key, raw, err)
			} else {
				cfg.TelConfig.MetricsPeriodicIntervalSec = v
			}
		}
	}
	{
		key := "TEL_EXPORT_INTERVAL_SEC"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("0")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.ExportIntervalSec", key, "0", err)
			} else {
				cfg.TelConfig.ExportIntervalSec = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.ExportIntervalSec", key, raw, err)
			} else {
				cfg.TelConfig.ExportIntervalSec = v
			}
		}
	}
	{
		key := "TEL_EXPORTER_WITH_INSECURE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithInsecure", key, "true", err)
			} else {
				cfg.TelConfig.WithInsecure = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithInsecure", key, raw, err)
			} else {
				cfg.TelConfig.WithInsecure = v
			}
		}
	}
	{
		key := "TEL_ENABLE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.Enable", key, "true", err)
			} else {
				cfg.TelConfig.Enable = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.Enable", key, raw, err)
			} else {
				cfg.TelConfig.Enable = v
			}
		}
	}
	{
		key := "TEL_ENABLE_COMPRESSION"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithCompression", key, "true", err)
			} else {
				cfg.TelConfig.WithCompression = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithCompression", key, raw, err)
			} else {
				cfg.TelConfig.WithCompression = v
			}
		}
	}
	{
		key := "TEL_SERVICE_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.Service = raw
		}
	}
	{
		key := "POD_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.Pod = raw
		}
	}
	{
		key := "NAMESPACE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.Namespace = "default"
		} else {
			cfg.Namespace = raw
		}
	}
	{
		key := "DEPLOY_ENVIRONMENT"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.Environment = "dev"
		} else {
			cfg.Environment = raw
		}
	}
	{
		key := "VERSION"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.Version = "dev"
		} else {
			cfg.Version = raw
		}
	}
	{
		key := "LOG_LEVEL"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.LogLevel = "info"
		} else {
			cfg.LogLevel = raw
		}
	}
	{
		key := "LOG_ENCODE"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			cfg.LogEncode = "console"
		} else {
			cfg.LogEncode = raw
		}
	}
	{
		key := "LOGS_MAX_MESSAGES_PER_SECOND"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseInt("0")
			if err != nil {
				env.AppendParse(&errs, "MaxMessagesPerSecond", key, "0", err)
			} else {
				cfg.MaxMessagesPerSecond = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "MaxMessagesPerSecond", key, raw, err)
			} else {
				cfg.MaxMessagesPerSecond = v
			}
		}
	}
	{
		key := "LOGS_MAX_LEVEL_MESSAGES_PER_SECOND"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
		} else {
			cfg.MaxLevelMessagesPerSecond = raw
		}
	}
	{
		key := "DEBUG"
		raw, ok := snap.Lookup(key)
		if !ok || raw == "" {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "Debug", key, "false", err)
			} else {
				cfg.Debug = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Debug", key, raw, err)
			} else {
				cfg.Debug = v
			}
		}
	}
	return env.NewError(errs)
}
