// Code generated by envgen. DO NOT EDIT.

package tel

import (
	env "github.com/gopherust-io/env"
)

func LoadConfig() (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, env.Snapshot()); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func ReloadConfig(cfg *Config) error {
	env.Reload()
	var next Config
	if err := loadConfig(&next, env.Snapshot()); err != nil {
		return err
	}
	*cfg = next
	return nil
}

func MustReloadConfig(cfg *Config) {
	if err := ReloadConfig(cfg); err != nil {
		panic(err)
	}
}

func LoadConfigFrom(snap *env.EnvSnapshot) (Config, error) {
	var cfg Config
	if err := loadConfig(&cfg, snap); err != nil {
		return cfg, err
	}
	return cfg, nil
}

func MustLoadConfig() Config {
	cfg, err := LoadConfig()
	if err != nil {
		panic(err)
	}
	return cfg
}

var configAuditSchema = []env.SchemaField{
	{Key: "MONITOR_ADDR", FieldPath: "MonitorConfig.MonitorAddr", Default: "127.0.0.1:8011", HasDefault: true},
	{Key: "MONITOR_ENABLE", FieldPath: "MonitorConfig.Enable", Default: "true", HasDefault: true},
	{Key: "TEL_COLLECTOR_GRPC_ADDR", FieldPath: "TelConfig.Address", Default: "127.0.0.1:4317", HasDefault: true},
	{Key: "TEL_COLLECTOR_TLS_SERVER_NAME", FieldPath: "TelConfig.ServerName"},
	{Key: "TEL_METRIC_PERIODIC_INTERVAL_SEC", FieldPath: "TelConfig.MetricsPeriodicIntervalSec", Default: "15", HasDefault: true},
	{Key: "TEL_EXPORT_INTERVAL_SEC", FieldPath: "TelConfig.ExportIntervalSec", Default: "0", HasDefault: true},
	{Key: "TEL_EXPORTER_WITH_INSECURE", FieldPath: "TelConfig.WithInsecure", Default: "true", HasDefault: true},
	{Key: "TEL_ENABLE", FieldPath: "TelConfig.Enable", Default: "true", HasDefault: true},
	{Key: "TEL_ENABLE_COMPRESSION", FieldPath: "TelConfig.WithCompression", Default: "true", HasDefault: true},
	{Key: "TEL_SERVICE_NAME", FieldPath: "Service"},
	{Key: "POD_NAME", FieldPath: "Pod"},
	{Key: "NAMESPACE", FieldPath: "Namespace", Default: "default", HasDefault: true},
	{Key: "DEPLOY_ENVIRONMENT", FieldPath: "Environment", Default: "dev", HasDefault: true},
	{Key: "VERSION", FieldPath: "Version", Default: "dev", HasDefault: true},
	{Key: "LOG_LEVEL", FieldPath: "LogLevel", Default: "info", HasDefault: true},
	{Key: "LOG_ENCODE", FieldPath: "LogEncode", Default: "console", HasDefault: true},
	{Key: "LOGS_MAX_MESSAGES_PER_SECOND", FieldPath: "MaxMessagesPerSecond", Default: "0", HasDefault: true},
	{Key: "LOGS_MAX_LEVEL_MESSAGES_PER_SECOND", FieldPath: "MaxLevelMessagesPerSecond"},
	{Key: "DEBUG", FieldPath: "Debug", Default: "false", HasDefault: true},
}

func AuditConfig(snap *env.EnvSnapshot) env.AuditReport {
	return env.Audit(snap, configAuditSchema, env.AuditOptions{})
}

func AuditConfigWithOptions(snap *env.EnvSnapshot, opts env.AuditOptions) env.AuditReport {
	return env.Audit(snap, configAuditSchema, opts)
}

func AuditConfigFromEnviron() env.AuditReport {
	return AuditConfig(env.Snapshot())
}

func loadConfig(cfg *Config, snap *env.EnvSnapshot) error {
	var errs []env.FieldError
	{
		key := "MONITOR_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "127.0.0.1:8011"
			cfg.MonitorConfig.MonitorAddr = v
		} else {
			cfg.MonitorConfig.MonitorAddr = raw
		}
	}
	{
		key := "MONITOR_ENABLE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "MonitorConfig.Enable", key, "true", err)
			} else {
				cfg.MonitorConfig.Enable = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "MonitorConfig.Enable", key, raw, err)
			} else {
				cfg.MonitorConfig.Enable = v
			}
		}
	}
	{
		key := "TEL_COLLECTOR_GRPC_ADDR"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "127.0.0.1:4317"
			cfg.TelConfig.Address = v
		} else {
			cfg.TelConfig.Address = raw
		}
	}
	{
		key := "TEL_COLLECTOR_TLS_SERVER_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.TelConfig.ServerName = raw
		}
	}
	{
		key := "TEL_METRIC_PERIODIC_INTERVAL_SEC"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("15")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.MetricsPeriodicIntervalSec", key, "15", err)
			} else {
				cfg.TelConfig.MetricsPeriodicIntervalSec = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.MetricsPeriodicIntervalSec", key, raw, err)
			} else {
				cfg.TelConfig.MetricsPeriodicIntervalSec = v
			}
		}
	}
	{
		key := "TEL_EXPORT_INTERVAL_SEC"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("0")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.ExportIntervalSec", key, "0", err)
			} else {
				cfg.TelConfig.ExportIntervalSec = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.ExportIntervalSec", key, raw, err)
			} else {
				cfg.TelConfig.ExportIntervalSec = v
			}
		}
	}
	{
		key := "TEL_EXPORTER_WITH_INSECURE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithInsecure", key, "true", err)
			} else {
				cfg.TelConfig.WithInsecure = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithInsecure", key, raw, err)
			} else {
				cfg.TelConfig.WithInsecure = v
			}
		}
	}
	{
		key := "TEL_ENABLE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.Enable", key, "true", err)
			} else {
				cfg.TelConfig.Enable = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.Enable", key, raw, err)
			} else {
				cfg.TelConfig.Enable = v
			}
		}
	}
	{
		key := "TEL_ENABLE_COMPRESSION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("true")
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithCompression", key, "true", err)
			} else {
				cfg.TelConfig.WithCompression = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "TelConfig.WithCompression", key, raw, err)
			} else {
				cfg.TelConfig.WithCompression = v
			}
		}
	}
	{
		key := "TEL_SERVICE_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.Service = raw
		}
	}
	{
		key := "POD_NAME"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.Pod = raw
		}
	}
	{
		key := "NAMESPACE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "default"
			cfg.Namespace = v
		} else {
			cfg.Namespace = raw
		}
	}
	{
		key := "DEPLOY_ENVIRONMENT"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "dev"
			cfg.Environment = v
		} else {
			cfg.Environment = raw
		}
	}
	{
		key := "VERSION"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "dev"
			cfg.Version = v
		} else {
			cfg.Version = raw
		}
	}
	{
		key := "LOG_LEVEL"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "info"
			cfg.LogLevel = v
		} else {
			cfg.LogLevel = raw
		}
	}
	{
		key := "LOG_ENCODE"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v := "console"
			cfg.LogEncode = v
		} else {
			cfg.LogEncode = raw
		}
	}
	{
		key := "LOGS_MAX_MESSAGES_PER_SECOND"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseInt("0")
			if err != nil {
				env.AppendParse(&errs, "MaxMessagesPerSecond", key, "0", err)
			} else {
				cfg.MaxMessagesPerSecond = v
			}
		} else {
			v, err := env.ParseInt(raw)
			if err != nil {
				env.AppendParse(&errs, "MaxMessagesPerSecond", key, raw, err)
			} else {
				cfg.MaxMessagesPerSecond = v
			}
		}
	}
	{
		key := "LOGS_MAX_LEVEL_MESSAGES_PER_SECOND"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
		} else {
			cfg.MaxLevelMessagesPerSecond = raw
		}
	}
	{
		key := "DEBUG"
		raw, ok := snap.Lookup(key)
		if !ok || env.IsEmpty(raw) {
			v, err := env.ParseBool("false")
			if err != nil {
				env.AppendParse(&errs, "Debug", key, "false", err)
			} else {
				cfg.Debug = v
			}
		} else {
			v, err := env.ParseBool(raw)
			if err != nil {
				env.AppendParse(&errs, "Debug", key, raw, err)
			} else {
				cfg.Debug = v
			}
		}
	}
	return env.NewError(errs)
}
